os: linux
dist: xenial

jobs:
  include:
    - os: windows
      language: shell
      before_install:
        - |-
          export JAVA_HOME=${JAVA_HOME:-/c/jdk}
          export MAVEN_HOME=${MAVEN_HOME:-/c/ProgramData/chocolatey/lib/maven/apache-maven-3.6.3}
          export PATH=${JAVA_HOME}/bin:${MAVEN_HOME}/bin:${PATH}
          choco install jdk8 -params 'installdir=c:\\jdk' -y
          choco install maven --version 3.6.3 -y
          java -version
          echo $MAVEN_HOME
          ls $MAVEN_HOME
          echo $MAVEN_HOME/bin
          ls $MAVEN_HOME/bin
          mvn -version

      script: mvn clean test

    - os: linux
      arch: amd64
      jdk: openjdk8
      script: mvn clean test

    - os: linux
      arch: amd64
      jdk: openjdk11
      script: mvn clean test

    - os: linux
      arch: arm64
      before_install:
        - sudo apt-get update
        - sudo apt-get -y install openjdk-8-jdk maven
      script: mvn clean test

    # Cannot install JDK 11 on Linux/arm64
    #    - os: linux
    #      arch: arm64
    #      before_install:
    #        - sudo apt-get update
    #        - sudo apt-get install -y openjdk-11-jdk maven
    #      script: mvn clean test

    - os: osx
      language: java
      osx_image: xcode7.3
      script: mvn clean test

    - os: osx
      language: java
      osx_image: xcode8.3
      script: mvn clean test

    - os: osx
      language: java
      osx_image: xcode9.3
      script: mvn clean test

    - os: osx
      language: java
      osx_image: xcode10.2
      script: mvn clean test

    - os: osx
      language: java
      osx_image: xcode11.4
      script: mvn clean test

install: true