/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luciad_imageio_webp_WebPReadParam */

#ifndef _Included_com_luciad_imageio_webp_WebPReadParam
#define _Included_com_luciad_imageio_webp_WebPReadParam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    createDecoderOptions
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luciad_imageio_webp_WebPReadParam_createDecoderOptions
  (JNIEnv *, jclass);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    deleteDecoderOptions
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_deleteDecoderOptions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getCropHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getCropHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setCropHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setCropHeight
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getCropLeft
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getCropLeft
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setCropLeft
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setCropLeft
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getCropTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getCropTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setCropTop
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setCropTop
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getCropWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getCropWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setCropWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setCropWidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isForceRotation
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isForceRotation
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setForceRotation
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setForceRotation
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isNoEnhancement
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isNoEnhancement
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setNoEnhancement
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setNoEnhancement
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isFancyUpsampling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isNoFancyUpsampling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setFancyUpsampling
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setNoFancyUpsampling
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getScaledHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getScaledHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setScaledHeight
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setScaledHeight
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    getScaledWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPReadParam_getScaledWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setScaledWidth
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setScaledWidth
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isUseCropping
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isUseCropping
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setUseCropping
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setUseCropping
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isUseScaling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isUseScaling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setUseScaling
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setUseScaling
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isUseThreads
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isUseThreads
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setUseThreads
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setUseThreads
  (JNIEnv *, jclass, jlong, jboolean);
  
/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    isBypassFiltering
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_luciad_imageio_webp_WebPReadParam_isBypassFiltering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPReadParam
 * Method:    setBypassFiltering
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPReadParam_setBypassFiltering
  (JNIEnv *, jclass, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
