/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luciad_imageio_webp_WebPWriteParam */

#ifndef _Included_com_luciad_imageio_webp_WebPWriteParam
#define _Included_com_luciad_imageio_webp_WebPWriteParam
#ifdef __cplusplus
extern "C" {
#endif
#undef com_luciad_imageio_webp_WebPWriteParam_MODE_DISABLED
#define com_luciad_imageio_webp_WebPWriteParam_MODE_DISABLED 0L
#undef com_luciad_imageio_webp_WebPWriteParam_MODE_DEFAULT
#define com_luciad_imageio_webp_WebPWriteParam_MODE_DEFAULT 1L
#undef com_luciad_imageio_webp_WebPWriteParam_MODE_EXPLICIT
#define com_luciad_imageio_webp_WebPWriteParam_MODE_EXPLICIT 2L
#undef com_luciad_imageio_webp_WebPWriteParam_MODE_COPY_FROM_METADATA
#define com_luciad_imageio_webp_WebPWriteParam_MODE_COPY_FROM_METADATA 3L
#undef com_luciad_imageio_webp_WebPWriteParam_MAX_MODE
#define com_luciad_imageio_webp_WebPWriteParam_MAX_MODE 3L
/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    createConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_createConfig
  (JNIEnv *, jclass);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    deleteConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_deleteConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getQuality
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setQuality
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setQuality
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getTargetSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getTargetSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setTargetSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setTargetSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getTargetPSNR
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getTargetPSNR
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setTargetPSNR
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setTargetPSNR
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setMethod
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setMethod
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getSegments
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getSegments
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setSegments
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setSegments
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getSnsStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getSnsStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setSnsStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setSnsStrength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getFilterStrength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getFilterStrength
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setFilterStrength
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setFilterStrength
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getFilterSharpness
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getFilterSharpness
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setFilterSharpness
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setFilterSharpness
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getFilterType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getFilterType
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setFilterType
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setFilterType
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getAutofilter
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getAutofilter
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setAutofilter
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setAutofilter
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getPass
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getPass
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setPass
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setPass
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getShowCompressed
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getShowCompressed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setShowCompressed
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setShowCompressed
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getPreprocessing
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getPreprocessing
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setPreprocessing
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setPreprocessing
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getPartitions
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getPartitions
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setPartitions
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setPartitions
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getPartitionLimit
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getPartitionLimit
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setPartitionLimit
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setPartitionLimit
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getAlphaCompression
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getAlphaCompression
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setAlphaCompression
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setAlphaCompression
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getAlphaFiltering
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getAlphaFiltering
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setAlphaFiltering
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setAlphaFiltering
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getAlphaQuality
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getAlphaQuality
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setAlphaQuality
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setAlphaQuality
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getLossless
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getLossless
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setLossless
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setLossless
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getEmulateJpegSize
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getEmulateJpegSize
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setEmulateJpegSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setEmulateJpegSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getThreadLevel
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getThreadLevel
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setThreadLevel
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setThreadLevel
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    getLowMemory
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_getLowMemory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_luciad_imageio_webp_WebPWriteParam
 * Method:    setLowMemory
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_luciad_imageio_webp_WebPWriteParam_setLowMemory
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
