/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luciad_imageio_webp_WebP */

#ifndef _Included_com_luciad_imageio_webp_WebP
#define _Included_com_luciad_imageio_webp_WebP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_luciad_imageio_webp_WebP
 * Method:    decode
 * Signature: (J[BII[IZ)[I
 */
JNIEXPORT jintArray JNICALL Java_com_luciad_imageio_webp_WebP_decode
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jintArray, jboolean);

/*
 * Class:     com_luciad_imageio_webp_WebP
 * Method:    getInfo
 * Signature: ([BII[I)I
 */
JNIEXPORT jint JNICALL Java_com_luciad_imageio_webp_WebP_getInfo
  (JNIEnv *, jclass, jbyteArray, jint, jint, jintArray);

/*
 * Class:     com_luciad_imageio_webp_WebP
 * Method:    encodeRGBA
 * Signature: (J[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_luciad_imageio_webp_WebP_encodeRGBA
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

/*
 * Class:     com_luciad_imageio_webp_WebP
 * Method:    encodeRGB
 * Signature: (J[BIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_luciad_imageio_webp_WebP_encodeRGB
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
